baseURL = "https://stuckathome.org/"
languageCode = "en-us"
title = "Stuck@Home"
theme = "prologue"

[params]
name = "Stuck@Home"
description = "A collaborative group of high school programming students"
long_description = "A consulting group of high school programming students; we go to hackathons and develop Python/web-based products."
copyright = "2018 Kevin Liu"