baseURL = "https://stuckathome.org/"
languageCode = "en-us"
title = "Stuck@Home"
theme = "prologue"

[params]
name = "Stuck@Home"
description = "A collaborative group of high school programming students"
long_description = "A consulting group of high school programming students - we go to hackathons and much more."
copyright = "2018 Kevin Liu"

# 3x3 grid of portfolio{1..3} with three rows
[[params.portfolio1]]
title = "Akira"
url = ""
source = ""
alt = ""

[[params.portfolio2]]
title = "Litcoin"
url = ""
source = ""
alt = ""

[[params.portfolio3]]
title = "Quecoin"
url = ""
source = ""
alt = ""